/**
 * Generates SQL to paste into Supabase SQL Editor.
 * Run: node prisma/generateSeedSQL.js > prisma/seed-schools.sql
 */
const COUNTRIES = [
  { name: 'Anguilla',                       code: 'AI' },
  { name: 'Antigua & Barbuda',              code: 'AG' },
  { name: 'British Virgin Islands',         code: 'VG' },
  { name: 'Dominica',                       code: 'DM' },
  { name: 'Grenada',                        code: 'GD' },
  { name: 'Saint Kitts & Nevis',            code: 'KN' },
  { name: 'Saint Lucia',                    code: 'LC' },
  { name: 'Saint Vincent & The Grenadines', code: 'VC' },
  { name: 'Other',                          code: 'OT' },
];

const SCHOOLS = [
  { name: 'Alwyn Allison Primary School', country: 'AI' },
  { name: 'Adrian T. Hazell Primary School', country: 'AI' },
  { name: 'Morris Vanterpool Primary School', country: 'AI' },
  { name: 'Orealia Kelly Primary School', country: 'AI' },
  { name: 'Valley Primary School', country: 'AI' },
  { name: 'Vivian Vanterpool Primary School', country: 'AI' },
  { name: 'Central Christian School', country: 'AI' },
  { name: 'Omololu International School', country: 'AI' },
  { name: 'Bendals Primary School', country: 'AG' },
  { name: 'Bethesda Primary School', country: 'AG' },
  { name: 'Bolans Primary School', country: 'AG' },
  { name: 'Buckleys Primary School', country: 'AG' },
  { name: 'Cedar Grove Primary School', country: 'AG' },
  { name: 'Cobbs Cross Primary School', country: 'AG' },
  { name: 'Five Islands Primary School', country: 'AG' },
  { name: 'Freemansville Primary School', country: 'AG' },
  { name: 'Freetown Primary School', country: 'AG' },
  { name: 'Golden Grove Primary School', country: 'AG' },
  { name: 'Greenbay Primary School', country: 'AG' },
  { name: 'Holy Trinity Primary School', country: 'AG' },
  { name: 'Jennings Primary School', country: 'AG' },
  { name: 'John Hughes Primary School', country: 'AG' },
  { name: 'J.T. Ambrose Primary School', country: 'AG' },
  { name: 'Liberta Primary School', country: 'AG' },
  { name: 'Mary E. Pigott Primary School', country: 'AG' },
  { name: 'New Winthorpes Primary School', country: 'AG' },
  { name: 'Newfield Primary School', country: 'AG' },
  { name: 'Old Road Primary School', country: 'AG' },
  { name: 'Pares Primary School', country: 'AG' },
  { name: 'Parham Primary School', country: 'AG' },
  { name: 'Pigotts Primary School', country: 'AG' },
  { name: 'Potters Primary School', country: 'AG' },
  { name: 'Sea View Farm Primary School', country: 'AG' },
  { name: 'T. N. Kirnon Primary School', country: 'AG' },
  { name: 'Urlings Primary School', country: 'AG' },
  { name: 'Villa Primary School', country: 'AG' },
  { name: 'Willikies Primary School', country: 'AG' },
  { name: 'Sunny Side Tutorial School', country: 'AG' },
  { name: 'Christian Faith Academy', country: 'AG' },
  { name: 'Christian Union Academy', country: 'AG' },
  { name: 'Foundation Mixed Primary School', country: 'AG' },
  { name: 'Goodwill Preparatory School', country: 'AG' },
  { name: 'Gospel Light Elementary School', country: 'AG' },
  { name: 'Grace Christian Academy', country: 'AG' },
  { name: 'Grays Crescent Primary School', country: 'AG' },
  { name: 'Greensville Primary School', country: 'AG' },
  { name: 'Island Academy International', country: 'AG' },
  { name: 'Kids Unlimited Primary School', country: 'AG' },
  { name: 'Minoah Magnet Academy', country: 'AG' },
  { name: 'New Bethel SDA Academy', country: 'AG' },
  { name: 'Post Millennial Academy', country: 'AG' },
  { name: 'St. Andrews Junior School', country: 'AG' },
  { name: "St. John's Catholic Primary School", country: 'AG' },
  { name: "St. John's Lutheran School", country: 'AG' },
  { name: "St. John's Temple Primary School", country: 'AG' },
  { name: "St. Michael's Primary School", country: 'AG' },
  { name: "St. Nicholas Primary School", country: 'AG' },
  { name: "St. Peter's Academy", country: 'AG' },
  { name: 'Sea View Academic Foundation', country: 'AG' },
  { name: 'Seventh Day Adventist School', country: 'AG' },
  { name: 'Sunnyside Tutorial Primary School', country: 'AG' },
  { name: 'T.O.R. Memorial Primary School', country: 'AG' },
  { name: 'Wesleyan Junior Academy', country: 'AG' },
  { name: 'Zion Primary School', country: 'AG' },
  { name: 'Enis Adams Primary School', country: 'VG' },
  { name: 'Belle Vue (Joyce Samuel) Primary School', country: 'VG' },
  { name: 'Ivan Dawson Primary School', country: 'VG' },
  { name: 'Leonora Delville Primary School', country: 'VG' },
  { name: 'Francis Lettsome Primary School', country: 'VG' },
  { name: 'Alexandrina Maduro Primary School', country: 'VG' },
  { name: 'Isabella Morris Primary School', country: 'VG' },
  { name: 'Ebenezer Thomas Primary School', country: 'VG' },
  { name: 'Willard Wheatley Primary School', country: 'VG' },
  { name: "St. George's Primary School", country: 'VG' },
  { name: 'Jost Van Dyke Primary School', country: 'VG' },
  { name: 'Althea Scatliffe Primary School', country: 'VG' },
  { name: 'Cedar International School', country: 'VG' },
  { name: 'Century House Montessori School B.V.I', country: 'VG' },
  { name: 'First Impressions School', country: 'VG' },
  { name: 'Pelican Gate School', country: 'VG' },
  { name: 'Agape Total Life Academy', country: 'VG' },
  { name: 'Atkinson Primary', country: 'DM' },
  { name: 'Belles Primary', country: 'DM' },
  { name: 'Castle Bruce Primary', country: 'DM' },
  { name: 'Concord Primary', country: 'DM' },
  { name: 'Delices Primary', country: 'DM' },
  { name: 'Grand Fond Primary', country: 'DM' },
  { name: 'Jones Baeupierre Primary', country: 'DM' },
  { name: 'Lighthouse Christian Academy', country: 'DM' },
  { name: 'Morne Jaune Primary', country: 'DM' },
  { name: 'Salybia Primary', country: 'DM' },
  { name: 'San Sauveur Primary', country: 'DM' },
  { name: 'Sineku Primary', country: 'DM' },
  { name: 'Warner Primary', country: 'DM' },
  { name: 'Berean Academy', country: 'DM' },
  { name: 'Convent Preparatory', country: 'DM' },
  { name: 'Coulibistrie Primary', country: 'DM' },
  { name: 'Campbell Primary', country: 'DM' },
  { name: 'Christian Union Primary', country: 'DM' },
  { name: 'Goodwill Primary', country: 'DM' },
  { name: 'Salisbury Primary', country: 'DM' },
  { name: 'Laudat Government School', country: 'DM' },
  { name: 'Temple SDA School', country: 'DM' },
  { name: 'School for the Hearing Impaired', country: 'DM' },
  { name: 'Dublanc Primary', country: 'DM' },
  { name: 'Giraudel Primary', country: 'DM' },
  { name: 'Ebenezer SDA Primary', country: 'DM' },
  { name: 'Pioneer Preparatory School', country: 'DM' },
  { name: 'Savanne Paille Primary', country: 'DM' },
  { name: 'Wills Strathmore Stevens Primary', country: 'DM' },
  { name: "St. Luke's Primary School", country: 'DM' },
  { name: 'Roseau Primary School', country: 'DM' },
  { name: 'Bonaire Government School', country: 'GD' },
  { name: 'Chantimelle R.C. Primary School', country: 'GD' },
  { name: 'Concord Government School', country: 'GD' },
  { name: 'Constantine Methodist School', country: 'GD' },
  { name: 'Corinth Government School', country: 'GD' },
  { name: 'Crochu R.C. School', country: 'GD' },
  { name: 'Dover Government School', country: 'GD' },
  { name: 'Florida Government School', country: 'GD' },
  { name: 'Grand Roy Government School', country: 'GD' },
  { name: 'Grenada Junior Academy', country: 'GD' },
  { name: 'Hermitage Government School', country: 'GD' },
  { name: 'Hillsborough Government School', country: 'GD' },
  { name: 'Holy Innocence Anglican School', country: 'GD' },
  { name: 'Mt. Pleasant Government School', country: 'GD' },
  { name: "Mt. Rose's Seventh-Day Adventist Primary School", country: 'GD' },
  { name: 'Paraclete Government School', country: 'GD' },
  { name: 'Seventh-Day Adventist Primary School', country: 'GD' },
  { name: 'South St. George Government School', country: 'GD' },
  { name: "St. Andrew's Methodist School", country: 'GD' },
  { name: "St. Dominic's R.C. School", country: 'GD' },
  { name: "St. George's Anglican Senior School", country: 'GD' },
  { name: "St. George's Methodist School", country: 'GD' },
  { name: "St. John's Anglican School", country: 'GD' },
  { name: "St. Louis R.C. Girls School", country: 'GD' },
  { name: "St. Mary's Junior School", country: 'GD' },
  { name: "St. Mary's Roman Catholic School", country: 'GD' },
  { name: "St. Patrick's Anglican Primary", country: 'GD' },
  { name: "St. Patrick's Roman Catholic Primary School", country: 'GD' },
  { name: "St. Paul's Government School", country: 'GD' },
  { name: "St. Peter's Roman Catholic School", country: 'GD' },
  { name: 'Telescope Primary School', country: 'GD' },
  { name: 'Vendome Roman Catholic School', country: 'GD' },
  { name: 'Westmorland Primary School', country: 'GD' },
  { name: "St. Andrew's Roman Catholic School", country: 'GD' },
  { name: 'Sacred Heart Catholic School Tivoli', country: 'GD' },
  { name: 'Estridge Primary School', country: 'KN' },
  { name: 'Joshua Obadiah Williams Primary School', country: 'KN' },
  { name: 'Sandy Point Primary School', country: 'KN' },
  { name: 'Beach Allen Primary School', country: 'KN' },
  { name: 'Cotton Thomas Comprehensive School', country: 'KN' },
  { name: 'Dr. William Connor Primary School', country: 'KN' },
  { name: 'Irishtown Primary School', country: 'KN' },
  { name: 'Maurice Hillier Memorial Junior School', country: 'KN' },
  { name: 'St. Kitts International Academy', country: 'KN' },
  { name: 'Immaculate Conception Catholic School', country: 'KN' },
  { name: 'St. Kitts Seventh-Day Adventist Primary School', country: 'KN' },
  { name: 'Tucker Clarke Primary School', country: 'KN' },
  { name: "St. Christopher's Preparatory School", country: 'KN' },
  { name: 'Dieppe Bay Primary School', country: 'KN' },
  { name: 'Edgar T. Morris Primary School', country: 'KN' },
  { name: 'Saddlers Primary School', country: 'KN' },
  { name: 'Cayon Primary School', country: 'KN' },
  { name: 'Violet Petty Primary School', country: 'KN' },
  { name: 'Newton Ground Primary School', country: 'KN' },
  { name: "St. Paul's Primary School", country: 'KN' },
  { name: 'Dean Glasford Primary School', country: 'KN' },
  { name: 'Tyrell Williams Primary School', country: 'KN' },
  { name: 'Bronte Welsh Primary School', country: 'KN' },
  { name: 'Nevis Academy', country: 'KN' },
  { name: 'Charlestown Primary School', country: 'KN' },
  { name: 'Ivor Walters Primary School', country: 'KN' },
  { name: 'Joycelyn Liburd Primary School', country: 'KN' },
  { name: 'Maude Crosse Preparatory School', country: 'KN' },
  { name: 'St. James Primary School', country: 'KN' },
  { name: 'Elizabeth Pemberton Primary School', country: 'KN' },
  { name: "St. Thomas Lowlands Primary School", country: 'KN' },
  { name: 'Violet O. Jeffers-Nicholls Primary School', country: 'KN' },
  { name: 'Montessori Academy Nevis', country: 'KN' },
  { name: 'Cecele Browne Integrated School', country: 'KN' },
  { name: 'Anse La Raye Infant & Primary School', country: 'LC' },
  { name: 'Augier Combined School', country: 'LC' },
  { name: 'Aux Leon Combined School', country: 'LC' },
  { name: 'Ave Maria Primary School', country: 'LC' },
  { name: 'Babonneau Primary School', country: 'LC' },
  { name: 'Balata Primary School', country: 'LC' },
  { name: 'Banse La Grace Combined School', country: 'LC' },
  { name: 'Belle Vue Combined School', country: 'LC' },
  { name: 'Bexon R.C. Infant & Primary School', country: 'LC' },
  { name: 'Blanchard Combined School', country: 'LC' },
  { name: 'Bouton Primary School', country: 'LC' },
  { name: 'Bocage Combined School', country: 'LC' },
  { name: 'Boguis Primary School', country: 'LC' },
  { name: 'Canaries Infant School', country: 'LC' },
  { name: 'Canaries Primary School', country: 'LC' },
  { name: 'Camille Henry Memorial School', country: 'LC' },
  { name: 'Canon Laurie Anglican Infant & Primary Schools', country: 'LC' },
  { name: 'Carmen Rene Memorial School', country: 'LC' },
  { name: 'Ciceron R.C. Combined School', country: 'LC' },
  { name: 'Dame Pearlette Louisy Primary School', country: 'LC' },
  { name: 'Delcer R.C. Combined School', country: 'LC' },
  { name: 'Deniere Riviere Combined School', country: 'LC' },
  { name: 'Dennery Infant School', country: 'LC' },
  { name: 'Desruisseaux Combined School', country: 'LC' },
  { name: 'Dugard Combined School', country: 'LC' },
  { name: 'Des Barras Combined School', country: 'LC' },
  { name: 'Emmanuel Seventh-day Adventist Combined School', country: 'LC' },
  { name: 'Eucharist Lewis Seventh-day Adventist Primary School', country: 'LC' },
  { name: 'Fond Assau Primary School', country: 'LC' },
  { name: 'Gordon and Walcott Memorial Methodist School', country: 'LC' },
  { name: 'Grace Combined School', country: 'LC' },
  { name: 'Grande-Riviere Primary School', country: 'LC' },
  { name: 'Gros Islet Primary School', country: 'LC' },
  { name: 'International School St. Lucia', country: 'LC' },
  { name: 'La Croix Maingot Primary School', country: 'LC' },
  { name: 'La Guerre Primary School', country: 'LC' },
  { name: 'La Ressource Combined School', country: 'LC' },
  { name: 'Laborie Girls & Boys Primary School', country: 'LC' },
  { name: "LAbayee Seventh-day Adventist Primary School", country: 'LC' },
  { name: 'Les Etangs Combined School', country: 'LC' },
  { name: 'Millet R.C. Infant & Primary School', country: 'LC' },
  { name: 'Monchy Combined School', country: 'LC' },
  { name: 'Mongouge Combined School', country: 'LC' },
  { name: 'Mon-Repos Combined School', country: 'LC' },
  { name: 'The Montessori Centre', country: 'LC' },
  { name: 'Morne Du Don Government Combined School', country: 'LC' },
  { name: 'Micoud Primary School', country: 'LC' },
  { name: 'Odsan Combined School', country: 'LC' },
  { name: 'Patience Combined School', country: 'LC' },
  { name: 'Plain View Combined School', country: 'LC' },
  { name: 'Piaye Combined School', country: 'LC' },
  { name: 'Pierrot Combined School', country: 'LC' },
  { name: 'Reunion Primary School', country: 'LC' },
  { name: 'Richford Primary School', country: 'LC' },
  { name: 'Riviere Doree Anglican School', country: 'LC' },
  { name: 'Roblot Government Combined School', country: 'LC' },
  { name: 'Roseau R.C. Combined School', country: 'LC' },
  { name: 'Saltibus Combined School', country: 'LC' },
  { name: 'Soufriere Primary School', country: 'LC' },
  { name: "St. Aloysius R.C. Boys Infant & Primary School", country: 'LC' },
  { name: 'Tapion Infant & Primary School', country: 'LC' },
  { name: 'Ti-Rocher Combined School', country: 'LC' },
  { name: 'Ti-Rocher Primary School', country: 'LC' },
  { name: 'Vide Boutielle Primary School', country: 'LC' },
  { name: 'Vieux-Fort Primary School', country: 'LC' },
  { name: 'Argyle Primary', country: 'VC' },
  { name: 'Ashton Government School', country: 'VC' },
  { name: 'Barrouallie Anglican Primary', country: 'VC' },
  { name: 'Barrouallie Government Primary', country: 'VC' },
  { name: 'Belair Government Primary', country: 'VC' },
  { name: 'Belmont Primary', country: 'VC' },
  { name: 'Bequia Anglican Primary', country: 'VC' },
  { name: 'Bequia S.D.A. Primary', country: 'VC' },
  { name: 'Biabou Methodist Primary', country: 'VC' },
  { name: 'Brighton Primary', country: 'VC' },
  { name: 'Buccament Government Primary', country: 'VC' },
  { name: 'C.W. Prescott Primary', country: 'VC' },
  { name: 'Calder Primary', country: 'VC' },
  { name: 'Calliaqua Anglican Primary', country: 'VC' },
  { name: 'Cane End Government Primary', country: 'VC' },
  { name: 'Canouan Government Primary', country: 'VC' },
  { name: 'Chateaubelair Methodist Primary', country: 'VC' },
  { name: 'Clare Valley Government Primary', country: 'VC' },
  { name: 'Colonarie Primary', country: 'VC' },
  { name: 'Diamond Government Primary', country: 'VC' },
  { name: 'Dorsetshire Hill Government Primary', country: 'VC' },
  { name: 'Evesham Methodist Primary', country: 'VC' },
  { name: 'Fair Hall Primary', country: 'VC' },
  { name: 'Fancy Government Primary', country: 'VC' },
  { name: 'Fitz-Hughes Government Primary', country: 'VC' },
  { name: 'Gomea Methodist Primary', country: 'VC' },
  { name: 'Kingstown Anglican Primary', country: 'VC' },
  { name: 'Kingstown Government Primary', country: 'VC' },
  { name: 'Kingstown Preparatory', country: 'VC' },
  { name: 'Langley Park Government Primary', country: 'VC' },
  { name: 'Lauders Government Primary', country: 'VC' },
  { name: 'Layou Government Primary', country: 'VC' },
  { name: 'Leeward District Seventh-Day Adventist Primary', country: 'VC' },
  { name: 'Lodge Village Government Primary', country: 'VC' },
  { name: 'Mary Hutchinson Primary', country: 'VC' },
  { name: 'Marriaqua Government Primary', country: 'VC' },
  { name: 'Mayreau Government Primary', country: 'VC' },
  { name: 'Mustique Government Primary', country: 'VC' },
  { name: 'New Grounds Primary', country: 'VC' },
  { name: 'Owia Government Primary', country: 'VC' },
  { name: 'Pamelus Burke Government Primary', country: 'VC' },
  { name: 'Paget Farm Government Primary', country: 'VC' },
  { name: 'Petersville Primary', country: 'VC' },
  { name: 'Questelles Government Primary', country: 'VC' },
  { name: 'Richland Park Government Primary', country: 'VC' },
  { name: 'Richland Park Seventh-Day Adventist Primary', country: 'VC' },
  { name: 'Rose Hall Government Primary', country: 'VC' },
  { name: 'Sandy Bay Government Primary', country: 'VC' },
  { name: 'Sion Hill Government Primary', country: 'VC' },
  { name: 'South Rivers Methodist Primary', country: 'VC' },
  { name: 'Spring Village Methodist Primary', country: 'VC' },
  { name: 'Stephanie Brown Primary', country: 'VC' },
  { name: "St. Mary's Roman Catholic Primary", country: 'VC' },
  { name: 'Stubbs Government Primary', country: 'VC' },
  { name: 'Sugar Mill Academy', country: 'VC' },
  { name: 'Troumaca Government Primary', country: 'VC' },
  { name: 'Westwood Methodist Primary', country: 'VC' },
  { name: 'Windsor Primary', country: 'VC' },
  { name: 'Berean Christian Academy', country: 'OT' },
];

const esc = s => s.replace(/'/g, "''");

const countryRows = COUNTRIES
  .map(c => `  (gen_random_uuid(), '${esc(c.name)}', '${c.code}', NOW())`)
  .join(',\n');

const schoolValues = SCHOOLS
  .map(s => `  ('${esc(s.name)}', '${s.country}')`)
  .join(',\n');

const sql = [
  '-- ================================================================',
  '-- OECS Countries & Schools seed',
  '-- Paste into Supabase SQL Editor and click Run.',
  '-- Safe to re-run (uses ON CONFLICT / WHERE NOT EXISTS).',
  '-- ================================================================',
  '',
  '-- 1. Countries',
  'INSERT INTO countries (id, name, code, created_at)',
  'VALUES',
  countryRows,
  'ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;',
  '',
  '-- 2. Schools (skip if name+country already exists)',
  'INSERT INTO schools (id, name, country_id, created_at, updated_at)',
  'SELECT gen_random_uuid(), s.name, c.id, NOW(), NOW()',
  'FROM (',
  '  VALUES',
  schoolValues,
  ') AS s(name, code)',
  'JOIN countries c ON c.code = s.code',
  'WHERE NOT EXISTS (',
  '  SELECT 1 FROM schools ex WHERE ex.name = s.name AND ex.country_id = c.id',
  ');',
  '',
  '-- Verify',
  'SELECT c.name AS country, COUNT(s.id) AS schools',
  'FROM countries c',
  'LEFT JOIN schools s ON s.country_id = c.id',
  'GROUP BY c.name',
  'ORDER BY c.name;',
].join('\n');

process.stdout.write(sql + '\n');
