// OHPC Kindergarten Assessment Data - Complete Curriculum Outcomes

export const assessmentData = {
  language_arts: [
    // Strand: Listening and Speaking
    { code: '1.1', strand: 'Listening and Speaking', description: 'listen to music, conversation and environmental sounds for personal enjoyment' },
    { code: '1.2', strand: 'Listening and Speaking', description: 'demonstrate interest, curiosity, engagement in sharing the experiences of others and with oral stories and information sharing' },
    { code: '1.3', strand: 'Listening and Speaking', description: 'use social listening and speaking skills to interact with a variety of audiences with sensitivity and respect' },
    { code: '1.4', strand: 'Listening and Speaking', description: 'interact and collaborate with the teacher and children who have diverse interests, backgrounds and languages' },
    { code: '1.5', strand: 'Listening and Speaking', description: 'become aware of how effective listening enhances understanding' },
    { code: '1.6', strand: 'Listening and Speaking', description: 'observe how tone, fluency and intonation impact meaning and mood' },
    { code: '1.7', strand: 'Listening and Speaking', description: 'use Home Language(s) and, as Standard English develops, share their thoughts, feelings and questions about engaging events, stories and conversations with increasing confidence' },
    { code: '1.8', strand: 'Listening and Speaking', description: 'develop increasing clarity and focus when sharing stories or experiences' },
    { code: '1.9', strand: 'Listening and Speaking', description: 'engage in active phonological awareness activities and word play to discriminate between various sounds in their environment, letters of the alphabet, rhyme and meaningful sound patterns' },
    { code: '1.10', strand: 'Listening and Speaking', description: 'develop and apply vocabulary and language structures to enhance their understanding of how to communicate ideas with purpose and focus' },

    // Strand: Reading and Viewing
    { code: '2.1', strand: 'Reading and Viewing', description: 'interact meaningfully with a wide range of genres and text forms' },
    { code: '2.2', strand: 'Reading and Viewing', description: 'develop questions when browsing through passages of interest' },
    { code: '2.3', strand: 'Reading and Viewing', description: 'connect background knowledge to the titles and pictures of fiction and nonfiction passages to build a foundation of understanding' },
    { code: '2.4', strand: 'Reading and Viewing', description: 'develop understanding and application of the Concepts of Print' },
    { code: '2.5', strand: 'Reading and Viewing', description: 'develop knowledge about the purpose and variety of texts that are read or read to them' },
    { code: '2.6', strand: 'Reading and Viewing', description: 'browse through a variety of images, and nonfiction material in pre-emergent and emergent level passages, or passages of interest, to discover information' },
    { code: '2.7', strand: 'Reading and Viewing', description: 'demonstrate understanding of some environmental print and pictorial information' },
    { code: '2.8', strand: 'Reading and Viewing', description: 'begin to apply comprehension strategies to visualize, predict and connect' },
    { code: '2.9', strand: 'Reading and Viewing', description: 'demonstrate understanding by responding to read-alouds with images, model making, discussions, or temporary writing' },
    { code: '2.10', strand: 'Reading and Viewing', description: 'connect words and images in pre-emergent and emergent level texts to background knowledge' },
    { code: '2.11', strand: 'Reading and Viewing', description: 'recognise and use a variety of high frequency words of personal importance, such as names and pre-emergent level high-frequency words' },
    { code: '2.12', strand: 'Reading and Viewing', description: 'participate in shared reading and use the meaning and flow of the language to anticipate upcoming words' },
    { code: '2.13', strand: 'Reading and Viewing', description: 'begin to demonstrate fluency and phrasing during shared reading, independent and guided reading of emergent level passages' },
    { code: '2.14', strand: 'Reading and Viewing', description: 'identify an increasing number of letter names and letter sounds, beginning with those of personal importance' },
    { code: '2.15', strand: 'Reading and Viewing', description: 'use known letter sounds to problem solve upcoming words in emergent level passages' },

    // Strand: Writing and Representing
    { code: '3.1', strand: 'Writing and Representing', description: 'use shared ideas to co-construct stories' },
    { code: '3.2', strand: 'Writing and Representing', description: 'assign meaning to experimental drawing and writing' },
    { code: '3.3', strand: 'Writing and Representing', description: 'begin expressive writing to share ideas and real and imagined topics' },
    { code: '3.4', strand: 'Writing and Representing', description: 'use peer collaboration and classroom tools to assist in writing process' },
    { code: '3.5', strand: 'Writing and Representing', description: 'learn to approximate and begin to refine printing of the lower case and upper case letters of the alphabet' },
    { code: '3.6', strand: 'Writing and Representing', description: 'connect spoken language(s) to written language and other representations (e.g. drawings)' },
    { code: '3.7', strand: 'Writing and Representing', description: 'connect phonological awareness to letter shapes' },
    { code: '3.8', strand: 'Writing and Representing', description: 'spell name and some words of personal importance correctly' },
  ],

  mathematics: [
    // Strand: Number Sense
    { code: '1.1.1', strand: 'Number Sense', description: 'Say the number sequence to 10 by 1s' },
    { code: '1.1.2', strand: 'Number Sense', description: 'Count backwards from 10 by 1s' },
    { code: '1.1.3', strand: 'Number Sense', description: 'Identify an error in counting sequence' },
    { code: '1.1.4', strand: 'Number Sense', description: 'Say the number that comes after a given number' },
    { code: '1.1.5', strand: 'Number Sense', description: 'Say the number that comes before a given number' },
    { code: '1.1.6', strand: 'Number Sense', description: 'Use a number line to support counting' },
    { code: '1.1.7', strand: 'Number Sense', description: 'Recite number names from a given number to a given number - i.e. start at a given number and go backwards down to 1 or start at a given number and go up to 10' },
    { code: '1.1.8', strand: 'Number Sense', description: 'Count with meaning to 10, by building quantities' },
    { code: '1.1.9', strand: 'Number Sense', description: 'Count with meaning to 10, by matching quantity and numeral' },
    { code: '1.2.1', strand: 'Number Sense', description: 'Represent a given number up to 10 using a variety of concrete models, including 5 and 10 frames' },
    { code: '1.2.2', strand: 'Number Sense', description: 'Answer the question, How many are in the set? using the last number counted in a set' },
    { code: '1.2.3', strand: 'Number Sense', description: 'In a fixed arrangement, starting in different locations, can show that the count of the number of objects in a set does not change' },
    { code: '1.2.4', strand: 'Number Sense', description: 'Count the number of objects in a given set, rearrange the objects, predict the new count, and recount to verify the prediction' },
    { code: '1.3.1', strand: 'Number Sense', description: 'Look briefly at a given familiar arrangement of one to five objects or dots and identify the number represented without counting' },
    { code: '1.3.2', strand: 'Number Sense', description: 'Look briefly at a given familiar arrangement of one to five objects or dots and identify the number represented by a given dot' },
    { code: '1.3.3', strand: 'Number Sense', description: 'Compare the number of objects in two sets of up to 10 objects, using phrases such as \'same number as\', \'equal to\', more than\', and \'less than' },
    { code: '1.3.4', strand: 'Number Sense', description: 'Make a set that has the same number of objects as a given set' },
    { code: '1.3.5', strand: 'Number Sense', description: 'Make a set that has one more object than a given set' },

    // Strand: Operations with Numbers
    { code: '2.1.1', strand: 'Operations with Numbers', description: 'Compose and decompose numbers up to 9 in a variety of ways using manipulatives, fingers and pictures (e.g. seven fingers held up, fold down two fingers, how many are left? Or, two blocks and two more blocks, how many altogether?). Symbolic representation (writing equations for composing and decomposing numbers) is an emerging outcome for end of Kindergarten' },

    // Strand: Pattern and Relationship
    { code: '3.1.1', strand: 'Pattern and Relationship', description: 'Create simple repeating patterns (2 elements)' },
    { code: '3.1.2', strand: 'Pattern and Relationship', description: 'Extend simple repeating patterns (2 elements)' },
    { code: '3.1.3', strand: 'Pattern and Relationship', description: 'Copy a given repeating pattern' },
    { code: '3.1.4', strand: 'Pattern and Relationship', description: 'Extend a variety of given repeating patterns to two more repetitions' },
    { code: '3.1.5', strand: 'Pattern and Relationship', description: 'Create a repeating pattern using manipulatives, musical instruments, or actions' },
    { code: '3.1.6', strand: 'Pattern and Relationship', description: 'Identify and describe a repeating pattern in the classroom, the school, and outdoors' },

    // Strand: Geometrical Thinking
    { code: '4.1.1', strand: 'Geometrical Thinking', description: 'Build and describe 3-D objects' },
    { code: '4.1.2', strand: 'Geometrical Thinking', description: 'Create a representation of a given 3-D object using building blocks, and compare the representation to the original 3-D object' },
    { code: '4.1.3', strand: 'Geometrical Thinking', description: 'Describe a given 3-D object using words such as big, little, round, like a box or a can' },
    { code: '4.2.1', strand: 'Geometrical Thinking', description: 'Identify and describe shapes (2-D = squares, circles, triangles, 3-D = cubes, cones, and spheres)' },
    { code: '4.2.2', strand: 'Geometrical Thinking', description: 'Describe objects in the environment using names of shapes and describe the relative positions of these objects using terms such as above, below, beside, in front of, behind, and next to' },
    { code: '4.2.3', strand: 'Geometrical Thinking', description: 'Correctly name shapes regardless of their orientations or overall size (2-D = squares, circles, triangles, 3-D = cubes, cones, and spheres)' },

    // Strand: Measurement
    { code: '5.1.1', strand: 'Measurement', description: 'Classify objects according to selected attributes, e.g., size, colour, shape, texture, sound, etc.' },
    { code: '5.1.2', strand: 'Measurement', description: 'Classify objects and count the number of objects in each category' },
    { code: '5.1.3', strand: 'Measurement', description: 'Describe several measurable attributes of a single object' },
    { code: '5.1.4', strand: 'Measurement', description: 'Directly compare two objects with a measurable attribute in common (such as length, weight) to see which object has "more of"/"less of" the attribute, and describe the difference. For example, directly compare the heights of two children and describe one child as taller/shorter' },
    { code: '5.2.1', strand: 'Measurement', description: 'Use non-standard units to measure attributes, e.g. uses blocks, hands span, toy cars, etc. to measure' },
    { code: '5.2.2', strand: 'Measurement', description: 'Identify days, weeks, months, holidays, and seasons (standard units of measure)' },
    { code: '5.2.3', strand: 'Measurement', description: 'Recite days of the week and months of the year in order' },
    { code: '5.2.4', strand: 'Measurement', description: 'Name the different monies (coins and notes) used in the Eastern Caribbean. (standard units of measure) by identifying the quantity in terms of cents' },

    // Strand: Data Management and Probability
    { code: '6.1.1', strand: 'Data Management and Probability', description: 'Collect simple sets of data in the class and school environment using observation' },
    { code: '6.1.2', strand: 'Data Management and Probability', description: 'Describe data classification' },
    { code: '6.1.3', strand: 'Data Management and Probability', description: 'Use counting to determine the number of objects in a group' },
    { code: '6.1.4', strand: 'Data Management and Probability', description: 'Describe the results of classification and data collection activities' },
  ],

  science: [
    // Strand: Forces and Interactions: Pushes and Pulls
    { code: '1.1.1', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that pushes can have different strengths and directions' },
    { code: '1.1.2', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that pulls can have different strengths and directions' },
    { code: '1.1.3', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that pushing or pulling on an object can change the speed or direction of its motion' },
    { code: '1.1.4', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that pushing on an object can start or stop it' },
    { code: '1.2.1', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that when objects touch or collide, they push on one another and can change motion' },
    { code: '1.2.2', strand: 'Forces and Interactions: Pushes and Pulls', description: 'Demonstrate that a bigger push or pull makes things speed up or slow down more quickly' },

    // Strand: Interdependent Relationships in Ecosystems: Animals, Plants, and Their Environment
    { code: '2.1.1', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand the difference between living and non-living things' },
    { code: '2.1.2', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand which living things are plants and which living things are animals' },
    { code: '2.1.3', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that humans are animals' },
    { code: '2.2.1', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand what "survive" means' },
    { code: '2.2.2', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that all living things need water' },
    { code: '2.2.3', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand plants need light to live and grow' },
    { code: '2.2.4', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that plants do not need to move around because they make their own food' },
    { code: '2.2.5', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that some plants need different things to survive than other plants' },
    { code: '2.2.6', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that all animals need food to live and grow. They obtain their food from plants or from other animals' },
    { code: '2.2.7', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that some animals need different kinds of food to survive from other animals' },
    { code: '2.2.8', strand: 'Interdependent Relationships in Ecosystems', description: 'Can give a specific example of how a plant or animal can change their environment to meet their needs' },
    { code: '2.2.9', strand: 'Interdependent Relationships in Ecosystems', description: 'Can explain that we know that plants and animals can change their environment because we have evidence' },
    { code: '2.3.1', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand why different plants and animals live where they do (their needs are met)' },
    { code: '2.3.2', strand: 'Interdependent Relationships in Ecosystems', description: 'Create a model to show where a plant or animal lives and what they find there that helps them to survive' },
    { code: '2.3.3', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand the way that plants and animals depend on each other and on the environment where they live - it\'s a system' },
    { code: '2.4.1', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that things that people do to live comfortably can affect the world around them' },
    { code: '2.4.2', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that we can do some things to reduce the impact of humans on the environment' },
    { code: '2.4.3', strand: 'Interdependent Relationships in Ecosystems', description: 'Understand that each child can make choices to reduce their impacts on the land, water, air, and other living things' },

    // Strand: Weather and Climate
    { code: '3.1.1', strand: 'Weather and Climate', description: 'Understand that sunlight can make a difference to things on the earth\'s surface' },
    { code: '3.1.2', strand: 'Weather and Climate', description: 'Observe that soil may change when the sun is shining' },
    { code: '3.1.3', strand: 'Weather and Climate', description: 'Observe that a wet rock may change when the sun is shining on it' },
    { code: '3.1.4', strand: 'Weather and Climate', description: 'Observe that a puddle may change when the sun is shining on it' },
    { code: '3.2.1', strand: 'Weather and Climate', description: 'Explain why people might want to reduce the warming effect of the sun' },
    { code: '3.2.2', strand: 'Weather and Climate', description: 'Name one thing people can build to minimize the warming effect of the sun - could be umbrellas, canopies, and tents' },
    { code: '3.2.3', strand: 'Weather and Climate', description: 'Explain one thing (asking questions, making observations, and gathering information) that people might do to solve problems like the warming effect of the sun' },
    { code: '3.2.4', strand: 'Weather and Climate', description: 'Tell one way that the child may protect themself and their belongings from the sun, or the rain' },
    { code: '3.2.5', strand: 'Weather and Climate', description: 'Design a structure that will keep the rain or sun off their play things at their house (this could be making a drawing of something that would keep the rain or sun off their play things)' },
    { code: '3.2.6', strand: 'Weather and Climate', description: 'Build a structure that will keep the rain or sun off their play things at their house (to do this, the children might use recycled objects to make a shelter for their toy car, or tricycle - whatever is relevant to their experience)' },
    { code: '3.3.1', strand: 'Weather and Climate', description: 'Understand that the weather makes a difference to people, plants and animals' },
    { code: '3.3.2', strand: 'Weather and Climate', description: 'Understand that people measure weather conditions to describe and record the weather and to notice patterns over time' },
    { code: '3.3.3', strand: 'Weather and Climate', description: 'Tell one example of a weather patterns could include that it is usually cooler in the morning than in the afternoon and the number of sunny days versus cloudy days is different in different months' },
    { code: '3.3.4', strand: 'Weather and Climate', description: 'List the seasons there are in their country' },
    { code: '3.3.5', strand: 'Weather and Climate', description: 'Keep track of descriptions of the weather (such as sunny, cloudy, rainy, and warm)' },
    { code: '3.3.6', strand: 'Weather and Climate', description: 'Keep track of numbers of sunny, windy, and rainy days in a month' },
    { code: '3.4.1', strand: 'Weather and Climate', description: 'Explain one way that people can find out what the weather forecast is' },
    { code: '3.4.2', strand: 'Weather and Climate', description: 'Tell who prepares a weather forecast' },
    { code: '3.4.3', strand: 'Weather and Climate', description: 'Understand that it is important to know if severe weather is coming so people can prepare for it' },
    { code: '3.4.4', strand: 'Weather and Climate', description: 'Understand that it is important to know if severe weather is coming so people can respond to it' },
    { code: '3.4.5', strand: 'Weather and Climate', description: 'Understand what is meant by the motto: Be prepared; not scared' },
    { code: '3.4.6', strand: 'Weather and Climate', description: 'List one kind of severe weather that might happen where they live' },
  ],

  social_studies: [
    // Strand: Myself - Historical and Cultural Thinking
    { code: '1.1.1', strand: 'Myself - Historical and Cultural Thinking', description: 'Demonstrate an understanding of "me" as a unique child' },
    { code: '1.1.2', strand: 'Myself - Historical and Cultural Thinking', description: 'Distinguish personal characteristics that make each child unique (physical traits, mannerisms)' },
    { code: '1.1.3', strand: 'Myself - Historical and Cultural Thinking', description: 'Appreciate that everyone has unique and special characteristics' },
    { code: '1.1.4', strand: 'Myself - Historical and Cultural Thinking', description: 'Express appreciation of the child\'s own personal attributes, one\'s name' },
    { code: '1.1.5', strand: 'Myself - Historical and Cultural Thinking', description: 'Name family members' },
    { code: '1.1.6', strand: 'Myself - Historical and Cultural Thinking', description: 'Represent family members using pictures/images' },
    { code: '1.1.7', strand: 'Myself - Historical and Cultural Thinking', description: 'Compare their physical features with those of their family members; categorize similarities and differences of self and other family members' },
    { code: '1.1.8', strand: 'Myself - Historical and Cultural Thinking', description: 'Understand that we inherit characteristics from our families' },
    { code: '1.1.9', strand: 'Myself - Historical and Cultural Thinking', description: 'Appreciate the uniqueness of families; respect that the composition of families takes many forms' },
    { code: '1.1.10', strand: 'Myself - Historical and Cultural Thinking', description: 'Understand that respect for self includes proper cleanliness, language and behaviour' },
    { code: '1.1.11', strand: 'Myself - Historical and Cultural Thinking', description: 'Categorize similarities and differences of self and others in families' },
    { code: '1.1.12', strand: 'Myself - Historical and Cultural Thinking', description: 'Recognize that their own physical characteristics, preferences, and mannerisms may be inherited from their families' },
    { code: '1.2.1', strand: 'Myself - Historical and Cultural Thinking', description: 'Name one religious and one national festival celebrated in their country' },
    { code: '1.2.2', strand: 'Myself - Historical and Cultural Thinking', description: 'Understand the significance and importance of religious and national festivals' },
    { code: '1.2.3', strand: 'Myself - Historical and Cultural Thinking', description: 'Appreciate that their country has different celebrations and traditions' },
    { code: '1.2.4', strand: 'Myself - Historical and Cultural Thinking', description: 'Identify customs (food, music, dance language) associated with these celebrations' },
    { code: '1.2.5', strand: 'Myself - Historical and Cultural Thinking', description: 'Make presentations on customs associated with these celebrations' },
    { code: '1.2.6', strand: 'Myself - Historical and Cultural Thinking', description: 'Appreciate the diversity of customs and take pride in this' },

    // Strand: Myself - Civic Participation
    { code: '2.1', strand: 'Myself - Civic Participation', description: 'Describe how family members care for one another' },
    { code: '2.2', strand: 'Myself - Civic Participation', description: 'Appreciate that family members love and care for one another' },
    { code: '2.3', strand: 'Myself - Civic Participation', description: 'Describe roles of various family members' },
    { code: '2.4', strand: 'Myself - Civic Participation', description: 'Chart the daily routines or activities in which family members care for one another' },
    { code: '2.5', strand: 'Myself - Civic Participation', description: 'Appreciate that the way family members love and care for one another helps them meet their basic needs' },
    { code: '2.6', strand: 'Myself - Civic Participation', description: 'Identify groups to which I belong' },
    { code: '2.7', strand: 'Myself - Civic Participation', description: 'Express how my behaviour in groups and the behaviour of others affects me and others' },
    { code: '2.8', strand: 'Myself - Civic Participation', description: 'Appreciate that members of groups to which I belong have responsibilities' },
    { code: '2.9', strand: 'Myself - Civic Participation', description: 'Recognize that all children have the right to be safe from harm' },
    { code: '2.10', strand: 'Myself - Civic Participation', description: 'List examples of what helps children feel safe' },
    { code: '2.11', strand: 'Myself - Civic Participation', description: 'Appreciate that being safe from harm also means that they must learn to play safely' },
    { code: '2.12', strand: 'Myself - Civic Participation', description: 'Demonstrate responsible caring behaviour towards others in play' },
    { code: '2.13', strand: 'Myself - Civic Participation', description: 'Identify national symbols and emblems such as the national flag, anthem, pledge, bird and flower' },
    { code: '2.14', strand: 'Myself - Civic Participation', description: 'Demonstrate appropriate behaviour when national anthem is being played, pledge is being said' },
    { code: '2.15', strand: 'Myself - Civic Participation', description: 'Appreciate and respect the importance of national symbols' },
    { code: '2.16', strand: 'Myself - Civic Participation', description: 'Know why we have rules in groups to which I belong (e.g. family, class at school)' },
    { code: '2.17', strand: 'Myself - Civic Participation', description: 'Apply groups\' rules in daily life' },
    { code: '2.18', strand: 'Myself - Civic Participation', description: 'Demonstrate examples of responsible and polite behaviour in groups to which I belong' },
    { code: '2.19', strand: 'Myself - Civic Participation', description: 'Describe safe practices while travelling to school' },
    { code: '2.20', strand: 'Myself - Civic Participation', description: 'Role play the use of safe practices when travelling to school' },
    { code: '2.21', strand: 'Myself - Civic Participation', description: 'Appreciate the value and benefits of practicing safety when travelling to school' },

    // Strand: Myself - Spatial Thinking
    { code: '3.1', strand: 'Myself - Spatial Thinking', description: 'State the name and address of their home and school' },
    { code: '3.2', strand: 'Myself - Spatial Thinking', description: 'Express themselves clearly when stating their address' },
    { code: '3.3', strand: 'Myself - Spatial Thinking', description: 'Feel a sense of belonging in their surroundings' },
    { code: '3.4', strand: 'Myself - Spatial Thinking', description: 'Identify natural and built features of the local environment' },
    { code: '3.5', strand: 'Myself - Spatial Thinking', description: 'Illustrate natural and built features of the local environment' },
    { code: '3.6', strand: 'Myself - Spatial Thinking', description: 'Appreciate that they are part of a wider environment' },
    { code: '3.7', strand: 'Myself - Spatial Thinking', description: 'Describe various weather conditions' },
    { code: '3.8', strand: 'Myself - Spatial Thinking', description: 'Observe and record different weather conditions' },
    { code: '3.9', strand: 'Myself - Spatial Thinking', description: 'Appreciate the importance of taking safety precautions in some weather conditions' },
  ],
};
